[phases.install]
cmd = "npm ci && npm install @rollup/rollup-linux-x64-gnu --no-save"

[phases.build]
cmd = """
echo "=== Starting Astro build ==="
npm run build
echo "=== Build completed ==="
echo "=== Checking dist directory ==="
ls -la dist/ || echo "No dist directory found"
echo "=== Checking index.html ==="
ls -la dist/index.html || echo "No index.html found"
echo "=== Dist directory contents ==="
find dist -type f | head -20 || echo "No files in dist"
"""

[phases.setup]
cmd = """
echo "=== Creating nginx web root if needed ==="
mkdir -p /usr/share/nginx/html
echo "=== Current nginx web root contents ==="
ls -la /usr/share/nginx/html/ || echo "No nginx web root found"
"""

[phases.deploy]
cmd = """
echo "=== Starting file deployment ==="
if [ -d "dist" ]; then
    echo "Found dist directory, copying files..."
    cp -rv dist/* /usr/share/nginx/html/
    echo "=== Files copied, checking nginx web root ==="
    ls -la /usr/share/nginx/html/
    echo "=== Verifying index.html in web root ==="
    ls -la /usr/share/nginx/html/index.html || echo "ERROR: index.html not found in web root"
else
    echo "ERROR: No dist directory found to deploy"
    exit 1
fi
"""

[variables]
NIXPACKS_BUILD_OUTPUT_DIR = "dist"
NIXPACKS_INSTALL_CMD = "npm ci"